changelog:
  categories:
    - title: Exciting Hyper New Features 🎉
      labels:
        - enhancement
    - title: Excellent Bug Fixes 🛠
      labels:
        - bug
    - title: Bump Dependencies 🔥
      labels:
        - dependencies
