name: Use env
description: test action

inputs:
  version:
    required: true
    description: "The version"
  level:
    default: "minor"
    required: false
    description: "Version up level：`major`, `minor`, `patch`"

outputs:
  current-version:
    value: ${{ inputs.version }}
    description: "Current version"
  next-version:
    value: ${{ steps.bump.outputs.next-version }}
    description: "Next version"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - run: "${GITHUB_ACTION_PATH}/script.sh"
      env:
        CURRENT_VERSION: ${{ inputs.version }}
        BUMP_LEVEL: ${{ inputs.level }}
      id: bump
      shell: bash
