name: Sharing Labeler
description: |
  This action serves as a convenient wrapper for [actions/labeler][labeler].
  Automatically label new pull requests based on the paths of files being changed or the branch name, similar to [actions/labeler][labeler].

  ## Usage

  You must create a YAML file to define your configuration.
  See details configuration syntax for labeler in [actions/labeler][labeler].

  ### Configuration URL

  ```yaml
    steps:
      - name: Sharing Labeler
        uses: tmknom/sharing-labeler-action@v0
        with:
          configuration-url: https://raw.githubusercontent.com/tmknom/sharing-labeler-action/main/configurations/conventional-commits.yml
  ```

  ### Configuration Path

  ```yaml
    steps:
      - name: Sharing Labeler
        uses: tmknom/sharing-labeler-action@v0
        with:
          configuration-path: .github/labeler.yml
  ```

inputs:
  configuration-url:
    required: false
    description: The url for the label configurations.
  configuration-path:
    required: false
    description: The path for the label configurations.

outputs:
  configuration-path:
    value: ${{ steps.config.outputs.path }}
    description: The path for the configuration file to passing actions/labeler.

runs:
  using: composite

  steps:
    - name: Start log group
      run: echo "::group::Sharing Labeler"
      shell: bash

    - name: Generate unique identifier
      id: unique
      run: |
        set -x
        random="$(openssl rand -base64 16 | tr -d '=' | tr -d '+' | tr -d '-')"
        identifier="${GITHUB_JOB}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-${GITHUB_SHA}-${random}"
        echo "identifier=${identifier}" >> "${GITHUB_OUTPUT}"
      shell: bash

    # curl options
    #
    # --silent: Silent or quiet mode.
    # --silent: When used with -s, --silent, it makes curl show an error message if it fails.
    # --location: If the server reports that the requested page has moved to a different location, redo the request on the new place.
    # --output <file>: Write output to <file> instead of stdout.
    - name: Download configuration
      id: download
      if: ${{ inputs.configuration-url != '' }}
      env:
        PREFIX: yamllint
        IDENTIFIER: ${{ steps.unique.outputs.identifier }}
        CONFIGURATION_URL: ${{ inputs.configuration-url }}
      run: |
        set -x
        config="${RUNNER_TEMP}/${PREFIX}-${IDENTIFIER}.yml"
        curl --silent --show-error --location --output "${config}" "${CONFIGURATION_URL}"
        echo "path=${config}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Validate configuration
      id: config
      env:
        CONFIG_PATH: ${{ steps.download.outputs.path || inputs.configuration-path }}
        DEFAULT_CONFIG_PATH: .github/labeler.yml
      run: |
        set -x
        if [[ "${CONFIG_PATH}" != "" && -f "${CONFIG_PATH}" ]]; then
          valid="${CONFIG_PATH}"
        elif [[ -f "${DEFAULT_CONFIG_PATH}" ]]; then
          valid="${DEFAULT_CONFIG_PATH}"
        else
          title="not found configuration file"
          detail="specify valid configuration-path or configuration-url"
          echo "::error:: ${title}: ${detail}"
          exit 1
        fi
        echo "path=${valid}" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Show configuration
      env:
        CONFIG_PATH: ${{ steps.config.outputs.path }}
      run: |
        set -x
        cat "${CONFIG_PATH}"
      shell: bash

    - name: End log group
      run: echo "::endgroup::"
      shell: bash

    - name: Labeler
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        sync-labels: true
        configuration-path: ${{ steps.config.outputs.path }}
