name: Cross Labeler
description: |
  This action serves as a convenient wrapper for [actions/labeler][labeler].
  Automatically assigning labels to new pull requests based on changed file paths or branch names, similar to [actions/labeler][labeler].

  ## Usage

  To set up the action, you need to create a YAML file that defines your configurations.
  Refer to the detailed configuration syntax for the labeler in [actions/labeler][labeler].

  ### Configuration Path

  ```yaml
    steps:
      - name: Cross Labeler
        uses: tmknom/cross-labeler-action@v0
        with:
          configuration-path: .github/labeler.yml
  ```

inputs:
  configuration-path:
    required: false
    description: The path for the label configurations.

runs:
  using: composite

  steps:
    - name: Labeler
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        sync-labels: true
        configuration-path: ${{ inputs.configuration-path || '.github/labeler.yml' }}
