name: Sharing Labeler
description: |
  This action serves as a convenient wrapper for [actions/labeler][labeler].
  Automatically label new pull requests based on the paths of files being changed or the branch name, similar to [actions/labeler][labeler].

  ## Usage

  You must create a YAML file to define your configuration.
  See details configuration syntax for labeler in [actions/labeler][labeler].

  ### Configuration Path

  ```yaml
    steps:
      - name: Sharing Labeler
        uses: tmknom/sharing-labeler-action@v0
        with:
          configuration-path: .github/labeler.yml
  ```

inputs:
  configuration-path:
    required: false
    description: The path for the label configurations.

runs:
  using: composite

  steps:
    - name: Labeler
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        sync-labels: true
        configuration-path: ${{ inputs.configuration-path }}
