name: Internal Label
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  call:
    # uses: tmknom/label-workflows/.github/workflows/composite-action.yml@v0
    uses: ./.github/workflows/reusable-label.yml
    permissions:
      contents: read
      pull-requests: write
