name: Docs Composite Action
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    env:
      BASE_BRANCH: ${{ inputs.branch }}
      PR_BRANCH: docs/${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ env.BASE_BRANCH }}

      # https://github.com/tmknom/actdocs
      - name: Inject document
        env:
          YAML_FILE: action.yml
          MD_FILE: README.md
        run: |
          set -x
          docker run --rm -v "$(pwd):/work" -w "/work" \
          ghcr.io/tmknom/actdocs inject --sort \
          --file "${MD_FILE}" "${YAML_FILE}"

      - name: Git config
        run: |
          set -x
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Git diff
        id: git
        run: |
          set -x
          if [[ "$(git status -s)" != "" ]]; then
            echo "diff=true" >> "${GITHUB_OUTPUT}"
          else
            echo "diff=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Push
        if: ${{ steps.git.outputs.diff == 'true' }}
        env:
          MESSAGE_TITLE: "docs: update README"
          MESSAGE_BODY: Generated by ${{ github.workflow }} / ${{ github.run_id }}-${{ github.run_attempt }}
        run: |
          set -x
          git switch -c "${PR_BRANCH}"
          git add .
          git commit -m "${MESSAGE_TITLE}" -m "${MESSAGE_BODY}"
          git push origin "${PR_BRANCH}" --force

      - name: Create PR
        if: ${{ steps.git.outputs.diff == 'true' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr create --base "${BASE_BRANCH}" --head "${PR_BRANCH}" --fill-first
