name: Example
on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  git-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Create
        run: |
          set -x
          date > test.txt

      - name: Git Push
        id: push
        uses: tmknom/git-push-action@7f731ecbcd08c4dce6bcf2b0b79d117f6cbc5864 # v0.2.0

      - name: View
        env:
          PUSHED: ${{ steps.push.outputs.pushed }}
          BRANCH: ${{ steps.push.outputs.branch }}
        run: |
          set -x
          echo "PUSHED=${PUSHED}"
          echo "BRANCH=${BRANCH}"
