name: Example
on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  git-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Create
        run: |
          set -x
          date > test.txt

      - name: Git Push
        id: push
        uses: tmknom/git-push-action@d88b186c540e4179bbb8e228b9c09e1a45677be7 # v0.2.1

      - name: View
        env:
          PUSHED: ${{ steps.push.outputs.pushed }}
          BRANCH: ${{ steps.push.outputs.branch }}
        run: |
          set -x
          echo "PUSHED=${PUSHED}"
          echo "BRANCH=${BRANCH}"
