name: Release GitHub Releases
on:
  workflow_call:
    inputs:
      bump-level:
        type: string
        required: true
        description: Determines which part of the version to increment [auto/patch/minor/major]

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          fetch-depth: 100

      - name: PR Label Bump Version
        id: pr-label
        if: ${{ inputs.bump-level == 'auto' }}
        uses: tmknom/pr-label-bump-version-action@f7bc41b17e98d6b258c7d4add4c789ad01c9964b # v0.1.0

      - name: Bump Version
        id: bump
        uses: tmknom/bump-version-action@87bed7f224292cab5b46a4cae9897bbf64153f00 # v0.2.1
        with:
          bump-level: ${{ steps.pr-label.outputs.level || inputs.bump-level }}

      - name: Push Version Tag
        uses: tmknom/push-version-tag-action@a9d1b46f9c29d3db510771452257b228bfd8a33f # v0.1.1
        with:
          version: ${{ steps.bump.outputs.version }}
          major: true

      - name: Release
        env:
          VERSION: ${{ steps.bump.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
