name: Release Go
on:
  workflow_call:
    inputs:
      bump-level:
        type: string
        required: true
        description: Bump up to [patch / minor / major]
      version-file:
        type: string
        default: go.mod
        required: false
        description: Path to the version file for Go, such as .go-version, go.mod or go.work.
    outputs:
      configuration-sha256:
        value: ${{ jobs.cross.outputs.configuration-sha256 }}
        description: SHA256 of the configuration file.

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: ${{ inputs.version-file }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Bump Version
        id: bump
        uses: tmknom/bump-version-action@87bed7f224292cab5b46a4cae9897bbf64153f00 # v0.2.1
        with:
          bump-level: ${{ inputs.bump-level }}

      - name: Push Version Tag
        uses: tmknom/push-version-tag-action@a9d1b46f9c29d3db510771452257b228bfd8a33f # v0.1.1
        with:
          version: ${{ steps.bump.outputs.version }}

      - name: Cross GoReleaser
        id: cross
        uses: tmknom/cross-goreleaser-action@f488f85702518d310748f0538d023e0f7990074e # v0.2.0
        with:
          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/feat/add-goreleaser-config/goreleaser/default.yml
#          configuration-url: https://raw.githubusercontent.com/tmknom/configurations/v0.4.0/goreleaser/default.yml
