name: JWT

on:
  workflow_dispatch:

jobs:
  call:
    # uses: ./.github/workflows/reusable-jwt.yml
    uses: tmknom/playground-workflows/.github/workflows/reusable-jwt.yml@3dce5bbde77ff5080b1daf86b9499544d8cb2a37
    permissions:
      contents: read
      id-token: write
