name: JWT

on:
  workflow_dispatch:

jobs:
  call:
    # uses: ./.github/workflows/reusable-jwt.yml
    uses: tmknom/playground-workflows/.github/workflows/reusable-jwt.yml@d6cc9b8cb1c8cb5e68306ea5baeb708adb2f9697
    permissions:
      contents: read
      id-token: write
