name: "Labeler"
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
