name: Label
on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label:
    uses: ./.github/workflows/reusable-workflows.yml
    permissions:
      contents: read
      pull-requests: write
