name: Merge
on:
  pull_request:
    paths: ["action.yml", ".github/workflows/*.yml"]

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: tmknom/merge-workflows/.github/workflows/github-actions.yml@feat/add-github-actions-workflow
    with:
      pull-request: ${{ github.event.pull_request.number }}
    permissions:
      contents: write
      pull-requests: write
