name: Random
on:
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: urandom
        shell: bash
        run: |
          set -x
          xxd -p -l 16 -c 16 /dev/urandom || true

      - name: Open SSL
        shell: bash
        run: |
          set -x
          openssl rand -base64 16 | tr -dc 'a-zA-Z0-9'

  macos:
    runs-on: macos-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: urandom
        shell: bash
        run: |
          set -x
          xxd -p -l 16 -c 16 /dev/urandom || true

      - name: Open SSL
        shell: bash
        run: |
          set -x
          openssl rand -base64 16 | tr -dc 'a-zA-Z0-9'

  windows:
    runs-on: windows-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: urandom
        shell: bash
        run: |
          set -x
          xxd -p -l 16 -c 16 /dev/urandom || true

      - name: Open SSL
        shell: bash
        run: |
          set -x
          openssl rand -base64 16 | tr -dc 'a-zA-Z0-9'
