name: Release
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        required: true
        description: Bump up to [auto / patch / minor / major]
        options:
          - auto
          - patch
          - minor
          - major
        default: auto

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: ./.github/workflows/go.yml
    with:
      bump-level: ${{ inputs.bump-level }}
      homebrew-tap-repository: homebrew-test-tap
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
