name: Docs Composite Action
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    env:
      BASE_BRANCH: ${{ github.event.repository.default_branch }}
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Generate unique identifier
        id: unique
        run: |
          set -x
          identifier="${GITHUB_JOB}-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}-${GITHUB_WORKFLOW_SHA}"
          echo "identifier=${identifier}" >> "${GITHUB_OUTPUT}"

      # https://github.com/tmknom/actdocs
      - name: Inject document
        env:
          YAML_FILE: action.yml
          MD_FILE: README.md
        run: |
          set -x
          docker run --rm -v "$(pwd):/work" -w "/work" \
          ghcr.io/tmknom/actdocs inject --sort \
          --file "${MD_FILE}" "${YAML_FILE}"

      - name: Git Config
        uses: tmknom/git-config-action@6ddb0c7929ae61b4bbfb5a0800d4ca72fa2584de # v0.1.0

      - name: Git Push
        id: push
        uses: tmknom/git-push-action@b81547a5d78b2de8032553306c611e9ff5f98f12 # v0.1.0

      - name: Create PR
        if: ${{ steps.push.outputs.pushed == 'true' }}
        env:
          BRANCH: ${{ steps.push.outputs.branch }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          gh pr create --base "${BASE_BRANCH}" --head "${BRANCH}" --fill-first
