name: Lint Reusable Workflows
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Lint YAML using yamllint
        uses: ./.github/actions/yamllint-action/first/

      - name: Run actionlint
        run: |
          set -x
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
