name: Label Reusable Workflows
on:
  workflow_call:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  label:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Labeler
        uses: ./.github/actions/labeler-action/first/
