name: Reusable JWT

on:
  workflow_call:

jobs:
  extract:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Retrieve OIDC Token
        id: oidc
        uses: ./.github/actions/retrieve-oidc-token-action/

      - name: Show payload
        env:
          PAYLOAD: ${{ steps.oidc.outputs.payload }}
        run: |
          jq . <<<"${PAYLOAD}"
