name: Reusable Docs
on:
  workflow_call:
    inputs:
      yaml-file:
        default: "action.yml"
        required: false
        type: string
        description: "The YAML file for the action or the reusable workflow"
      markdown-file:
        default: "README.md"
        required: false
        type: string
        description: "The Markdown file for the injection target"
      ref:
        required: true
        type: string
        description: "The git ref"
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      YAML_FILE: ${{ inputs.yaml-file }}
      MD_FILE: ${{ inputs.markdown-file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Inject document
        run: |
          docker run --rm -v "$(pwd):/work" -w "/work" \
          ghcr.io/tmknom/actdocs inject --sort \
          --file "${MD_FILE}" "${YAML_FILE}"

      - name: Git push
        run: |
          if [[ "$(git status -s)" == "" ]]; then
            echo 'skipped'
            exit 0
          fi
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${MD_FILE}"
          git commit -m "Update ${MD_FILE}"
          git push
